export const names = [
    '01: Bratislavská korunovačná cesta 1563-1830',
    '02: Uhorskí panovníci',
    '03: Maximilián I. a Mária Španielska',
    '04: Rudolf II.',
    '05: Matej II. a Anna Tirolská',
    '06: Ferdinand II.',
    '07: Mária Anna, Eleonóra Toskánska',
    '08: Ferdinand IV.',
    '09: Leopold I.',
    '10: Jozef I.',
    '11: Karol III. a Alžbeta Kristína',
    '12: Mária Terézia',
    '13: Leopold II.',
    '14: Mária Ludovika, Karolína Augusta',
    '15: Ferdinand V.',
    '01: Royal coronations at Bratislava 1563-1830',
    '02: Hungarian rulers',
    '03: Maximilian I and Maria of Spain',
    '04: Rudolf II',
    '05: Matthias II and Anna of Tyrol',
    '06: Ferdinand II',
    '07: Maria Anna, Eleonora Gonzaga',
    '08: Ferdinand IV',
    '09: Leopold I',
    '10: Joseph I',
    '11: Charles III and Elisabeth Christine',
    '12: Maria Theresa',
    '13: Leopold II',
    '14: Maria Ludovika, Caroline Augusta',
    '15: Ferdinand V'
];